COMPONENT=UAgriC
CFLAGS += -I$(TOSDIR)/sensorboards/SBT80
CFLAGS += -I$(TOSDIR)/chips/sht7x
CFLAGS += -I$(TOSDIR)/platforms/telosa/chips/sht7x


PFLAGS += -DCC2420_DEF_CHANNEL=20
include $(MAKERULES)
