COMPONENT=MultihopOscilloscopeAppC
CFLAGS += -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle
#PFLAGS+=-DLOW_POWER_LISTENING
PFLAGS+=-DCC2420_DEF_CHANNEL=26

include $(MAKERULES)
