COMPONENT=TestDisseminationAppC
#COMPONENT=TestDisseminationAppBasicC

### For Drip:
CFLAGS += -I$(TOSDIR)/lib/net -I%T/lib/net/drip

PFLAGS+=-DCC2420_DEF_CHANNEL=20
PFLAGS+=-DRF230_DEF_CHANNEL=19

### For DIP:
#CFLAGS += -I$(TOSDIR)/lib/net -I%T/lib/net/dip -I%T/lib/net/dip/interfaces


include $(MAKERULES)

